<?php

function writeInshokutenContainer()
{
	print('<div class="inshokuten_container">');
		print('<div class="registory_inshokuten_container">');
			print('<div class="edit_inshokuten_title">飲食店情報 登録・編集</div>');
			print('<div class="edit_inshokuten_note">');
				print('登録・編集する情報に誤りがないことをご確認ください。また、入力された情報が事実と異なる場合、管理者側から修正・削除させていただくことがございますので、ご了承ください。');
			print('</div>');
			print('<form class="inshokuten_form" name="form">');
				print('<div class="inshokuten_wrapper">');
					print('<div class="row_container">');
						print('<div class="row_title_container">');
							print('<div class="row_title_sign"></div>');
							print('<div class="row_title">飲食店の名称<span>必須</span></div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">店名</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_name">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">ひらがな</div>');
								print('<span>全角かな</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_read">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">ローマ字</div>');
								print('<span>半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_english">');
							print('</div>');
						print('</div>');
						/*print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">その他の店名 ※上記以外の旧字体・異字体(例:桜/櫻など)を含む店名も登録したい場合は以下に入力してください</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="sakagura_search[]">');
							print('</div>');
						print('</div>');*/
					print('</div>');

					print('<div class="row_container">');
						print('<div class="row_title_container">');
							print('<div class="row_title_sign"></div>');
							print('<div class="row_title">住所</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">郵便番号</div>');
								print('<span>半角数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" size="24" name="inshokuten_postalcode">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">都道府県</div>');
							print('</div>');
							print('<div class="column2">');
								print('<SELECT read="" name="inshokuten_pref">');
									print('<OPTION VALUE="" read="">----</OPTION>');
									print('<OPTION VALUE="北海道" read="ほっかいどう">北海道</OPTION>');
									print('<OPTION VALUE="青森県" read="あおもりけん">青森県</OPTION>');
									print('<OPTION VALUE="岩手県" read="いわてけん">岩手県</OPTION>');
									print('<OPTION VALUE="宮城県" read="みやぎけん">宮城県</OPTION>');
									print('<OPTION VALUE="秋田県" read="あきたけん">秋田県</OPTION>');
									print('<OPTION VALUE="山形県" read="やまがたけん">山形県</OPTION>');
									print('<OPTION VALUE="福島県" read="ふくしまけん">福島県</OPTION>');
									print('<OPTION VALUE="茨城県" read="いばらぎけん">茨城県</OPTION>');
									print('<OPTION VALUE="栃木県" read="とちぎけん">栃木県</OPTION>');
									print('<OPTION VALUE="群馬県" read="ぐんまけん">群馬県</OPTION>');
									print('<OPTION VALUE="埼玉県" read="さいたまけん">埼玉県</OPTION>');
									print('<OPTION VALUE="千葉県" read="ちばけん">千葉県</OPTION>');
									print('<OPTION VALUE="東京都" read="とうきょうと">東京都</OPTION>');
									print('<OPTION VALUE="神奈川県" read="かながわけん">神奈川県</OPTION>');
									print('<OPTION VALUE="新潟県" read="にいがたけん">新潟県</OPTION>');
									print('<OPTION VALUE="富山県" read="とやまけん">富山県</OPTION>');
									print('<OPTION VALUE="石川県" read="いしかわけん">石川県</OPTION>');
									print('<OPTION VALUE="福井県" read="ふくいけん">福井県</OPTION>');
									print('<OPTION VALUE="山梨県" read="やまなしけん">山梨県</OPTION>');
									print('<OPTION VALUE="長野県" read="ながのけん">長野県</OPTION>');
									print('<OPTION VALUE="岐阜県" read="ぎふけん">岐阜県</OPTION>');
									print('<OPTION VALUE="静岡県" read="しずおかけん">静岡県</OPTION>');
									print('<OPTION VALUE="愛知県" read="あいちけん">愛知県</OPTION>');
									print('<OPTION VALUE="三重県" read="みえけん">三重県</OPTION>');
									print('<OPTION VALUE="滋賀県" read="しがけん">滋賀県</OPTION>');
									print('<OPTION VALUE="京都府" read="きょうとふ">京都府</OPTION>');
									print('<OPTION VALUE="大阪府" read="おおさかふ">大阪府</OPTION>');
									print('<OPTION VALUE="兵庫県" read="ひょうごけん">兵庫県</OPTION>');
									print('<OPTION VALUE="奈良県" read="ならけん">奈良県</OPTION>');
									print('<OPTION VALUE="和歌山県" read="わかやまけん">和歌山県</OPTION>');
									print('<OPTION VALUE="鳥取県" read="とっとりけん">鳥取県</OPTION>');
									print('<OPTION VALUE="島根県" read="しまねけん">島根県</OPTION>');
									print('<OPTION VALUE="岡山県" read="おかやまけん">岡山県</OPTION>');
									print('<OPTION VALUE="広島県" read="ひろしまけん">広島県</OPTION>');
									print('<OPTION VALUE="山口県" read="やまぐちけん">山口県</OPTION>');
									print('<OPTION VALUE="徳島県" read="とくしまけん">徳島県</OPTION>');
									print('<OPTION VALUE="香川県" read="かがわけん">香川県</OPTION>');
									print('<OPTION VALUE="愛媛県" read="えひめけん">愛媛県</OPTION>');
									print('<OPTION VALUE="高知県" read="こうちけん">高知県</OPTION>');
									print('<OPTION VALUE="福岡県" read="ふくおかけん">福岡県</OPTION>');
									print('<OPTION VALUE="佐賀県" read="さがけん">佐賀県</OPTION>');
									print('<OPTION VALUE="長崎県" read="ながさきけん">長崎県</OPTION>');
									print('<OPTION VALUE="熊本県" read="くまもとけん">熊本県</OPTION>');
									print('<OPTION VALUE="大分県" read="おおいたけん">大分県</OPTION>');
									print('<OPTION VALUE="宮崎県" read="みやざきけん">宮城県</OPTION>');
									print('<OPTION VALUE="鹿児島県" read="かごしまけん">鹿児島県</OPTION>');
									print('<OPTION VALUE="沖縄県" read="おきなわけん">沖縄県</OPTION>');
								print('</SELECT>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">市区町村・番地</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_address">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">建物名・階数</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_address2">');
							print('</div>');
						print('</div>');
					print('</div>');

					print('<div class="row_container">');
						print('<div class="row_title_container">');
							print('<div class="row_title_sign"></div>');
							print('<div class="row_title">問い合わせ先</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">電話番号</div>');
								print('<span>半角数字</span>');
							print('</div>');
							print('<div class="column2"><input type="text" name="inshokuten_phone"></div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">Email</div>');
								print('<span>半角英数字</span>');
							print('</div>');
							print('<div class="column2"><input type="text" name="inshokuten_email"></div>');
						print('</div>');
					print('</div>');

					print('<div class="row_container">');
						print('<div class="row_title_container">');
							print('<div class="row_title_sign"></div>');
							print('<div class="row_title">詳細情報</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">店舗までのアクセス</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2"><textarea name="inshokuten_station_optional"></textarea></div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">営業時間</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2"><textarea name="inshokuten_hours"></textarea></div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">定休日</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_holiday">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">ジャンル1</div>');
							print('</div>');
							print('<div class="column2">');
								print('<SELECT name="inshokuten_main_genre">');
									print('<OPTION VALUE="">----</OPTION>');
									print('<OPTION VALUE="居酒屋">居酒屋</OPTION>');
									print('<OPTION VALUE="レストラン">レストラン</OPTION>');
									print('<OPTION VALUE="ビストロ">ビストロ</OPTION>');
									print('<OPTION VALUE="バー・バル">バー・バル</OPTION>');
									print('<OPTION VALUE="立ち飲み">立ち飲み</OPTION>');
									print('<OPTION VALUE="角打ち">角打ち</OPTION>');
									print('<OPTION VALUE="魚介・海鮮料理">魚介・海鮮料理</OPTION>');
									print('<OPTION VALUE="寿司">寿司</OPTION>');
									print('<OPTION VALUE="懐石料理">懐石料理</OPTION>');
									print('<OPTION VALUE="割烹・小料理">割烹・小料理</OPTION>');
									print('<OPTION VALUE="そば">そば</OPTION>');
									print('<OPTION VALUE="うどん">うどん</OPTION>');
									print('<OPTION VALUE="麺料理">麺料理</OPTION>');
									print('<OPTION VALUE="鍋料理・すき焼き・しゃぶしゃぶ">鍋料理・すき焼き・しゃぶしゃぶ</OPTION>');
									print('<OPTION VALUE="うなぎ">うなぎ</OPTION>');
									print('<OPTION VALUE="おでん">おでん</OPTION>');
									print('<OPTION VALUE="丼もの">丼もの</OPTION>');
									print('<OPTION VALUE="お好み焼き・もんじゃ焼き">お好み焼き・もんじゃ焼き</OPTION>');
									print('<OPTION VALUE="焼き鳥・串料理">焼き鳥・串料理</OPTION>');
									print('<OPTION VALUE="焼肉">焼肉</OPTION>');
									print('<OPTION VALUE="鉄板焼き・ステーキ">鉄板焼き・ステーキ</OPTION>');
									print('<OPTION VALUE="肉料理">肉料理</OPTION>');
									print('<OPTION VALUE="フレンチ">フレンチ</OPTION>');
									print('<OPTION VALUE="イタリアン">イタリアン</OPTION>');
									print('<OPTION VALUE="中華料理">中華料理</OPTION>');
									print('<OPTION VALUE="料理持ち込み">料理持ち込み</OPTION>');
									print('<OPTION VALUE="その他">その他</OPTION>');
								print('</SELECT>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">ジャンル2</div>');
							print('</div>');
							print('<div class="column2">');
								print('<SELECT name="inshokuten_sub_genre">');
									print('<OPTION VALUE="">----</OPTION>');
									print('<OPTION VALUE="居酒屋">居酒屋</OPTION>');
									print('<OPTION VALUE="レストラン">レストラン</OPTION>');
									print('<OPTION VALUE="ビストロ">ビストロ</OPTION>');
									print('<OPTION VALUE="バー・バル">バー・バル</OPTION>');
									print('<OPTION VALUE="立ち飲み">立ち飲み</OPTION>');
									print('<OPTION VALUE="角打ち">角打ち</OPTION>');
									print('<OPTION VALUE="魚介・海鮮料理">魚介・海鮮料理</OPTION>');
									print('<OPTION VALUE="寿司">寿司</OPTION>');
									print('<OPTION VALUE="懐石料理">懐石料理</OPTION>');
									print('<OPTION VALUE="割烹・小料理">割烹・小料理</OPTION>');
									print('<OPTION VALUE="そば">そば</OPTION>');
									print('<OPTION VALUE="うどん">うどん</OPTION>');
									print('<OPTION VALUE="麺料理">麺料理</OPTION>');
									print('<OPTION VALUE="鍋料理・すき焼き・しゃぶしゃぶ">鍋料理・すき焼き・しゃぶしゃぶ</OPTION>');
									print('<OPTION VALUE="うなぎ">うなぎ</OPTION>');
									print('<OPTION VALUE="おでん">おでん</OPTION>');
									print('<OPTION VALUE="丼もの">丼もの</OPTION>');
									print('<OPTION VALUE="お好み焼き・もんじゃ焼き">お好み焼き・もんじゃ焼き</OPTION>');
									print('<OPTION VALUE="焼き鳥・串料理">焼き鳥・串料理</OPTION>');
									print('<OPTION VALUE="焼肉">焼肉</OPTION>');
									print('<OPTION VALUE="鉄板焼き・ステーキ">鉄板焼き・ステーキ</OPTION>');
									print('<OPTION VALUE="肉料理">肉料理</OPTION>');
									print('<OPTION VALUE="フレンチ">フレンチ</OPTION>');
									print('<OPTION VALUE="イタリアン">イタリアン</OPTION>');
									print('<OPTION VALUE="中華料理">中華料理</OPTION>');
									print('<OPTION VALUE="料理持ち込み">料理持ち込み</OPTION>');
									print('<OPTION VALUE="その他">その他</OPTION>');
								print('</SELECT>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">ジャンル3</div>');
							print('</div>');
							print('<div class="column2">');
								print('<SELECT name="inshokuten_sub_genre2">');
									print('<OPTION VALUE="">----</OPTION>');
									print('<OPTION VALUE="居酒屋">居酒屋</OPTION>');
									print('<OPTION VALUE="レストラン">レストラン</OPTION>');
									print('<OPTION VALUE="ビストロ">ビストロ</OPTION>');
									print('<OPTION VALUE="バー・バル">バー・バル</OPTION>');
									print('<OPTION VALUE="立ち飲み">立ち飲み</OPTION>');
									print('<OPTION VALUE="角打ち">角打ち</OPTION>');
									print('<OPTION VALUE="魚介・海鮮料理">魚介・海鮮料理</OPTION>');
									print('<OPTION VALUE="寿司">寿司</OPTION>');
									print('<OPTION VALUE="懐石料理">懐石料理</OPTION>');
									print('<OPTION VALUE="割烹・小料理">割烹・小料理</OPTION>');
									print('<OPTION VALUE="そば">そば</OPTION>');
									print('<OPTION VALUE="うどん">うどん</OPTION>');
									print('<OPTION VALUE="麺料理">麺料理</OPTION>');
									print('<OPTION VALUE="鍋料理・すき焼き・しゃぶしゃぶ">鍋料理・すき焼き・しゃぶしゃぶ</OPTION>');
									print('<OPTION VALUE="うなぎ">うなぎ</OPTION>');
									print('<OPTION VALUE="おでん">おでん</OPTION>');
									print('<OPTION VALUE="丼もの">丼もの</OPTION>');
									print('<OPTION VALUE="お好み焼き・もんじゃ焼き">お好み焼き・もんじゃ焼き</OPTION>');
									print('<OPTION VALUE="焼き鳥・串料理">焼き鳥・串料理</OPTION>');
									print('<OPTION VALUE="焼肉">焼肉</OPTION>');
									print('<OPTION VALUE="鉄板焼き・ステーキ">鉄板焼き・ステーキ</OPTION>');
									print('<OPTION VALUE="肉料理">肉料理</OPTION>');
									print('<OPTION VALUE="フレンチ">フレンチ</OPTION>');
									print('<OPTION VALUE="イタリアン">イタリアン</OPTION>');
									print('<OPTION VALUE="中華料理">中華料理</OPTION>');
									print('<OPTION VALUE="料理持ち込み">料理持ち込み</OPTION>');
									print('<OPTION VALUE="その他">その他</OPTION>');
								print('</SELECT>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">日本酒メニュー</div>');
							print('</div>');
							print('<div class="column2_checkradio">');
								print('<label><input type="radio" name="inshokuten_sake_count" value="1">～10種類</label>');
								print('<label><input type="radio" name="inshokuten_sake_count" value="2">11～20種類</label>');
								print('<label><input type="radio" name="inshokuten_sake_count" value="3">21～30種類</label>');
								print('<label><input type="radio" name="inshokuten_sake_count" value="4">31～40種類</label>');
								print('<label><input type="radio" name="inshokuten_sake_count" value="5">41～50種類</label>');
								print('<label><input type="radio" name="inshokuten_sake_count" value="6">51～70種類</label>');
								print('<label><input type="radio" name="inshokuten_sake_count" value="7">71～100種類</label>');
								print('<label><input type="radio" name="inshokuten_sake_count" value="8">101種類～</label>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">サービスの特徴</div>');
							print('</div>');
							print('<div class="column2_checkradio">');
								print('<label><input type="checkbox" name="inshokuten_store_style[]" value="1">日本酒中心のドリンクメニュー</label>');
								print('<label><input type="checkbox" name="inshokuten_store_style[]" value="2">プレミア銘柄・人気銘柄の日本酒を飲める</label>');
								print('<label><input type="checkbox" name="inshokuten_store_style[]" value="3">1杯500円以下で日本酒を飲める</label>');
								print('<label><input type="checkbox" name="inshokuten_store_style[]" value="4">日本酒飲み放題あり</label>');
								print('<label><input type="checkbox" name="inshokuten_store_style[]" value="5">日本酒セルフ式</label>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">予算</div>');
							print('</div>');
							print('<div class="column2">');
								print('<SELECT read="" name="inshokuten_budget">');
									print('<OPTION VALUE="">----</OPTION>');
									print('<OPTION VALUE="～999円">～999円</OPTION>');
									print('<OPTION VALUE="1,000～1,999円">1,000～1,999円</OPTION>');
									print('<OPTION VALUE="2,000～2,999円">2,000～2,999円</OPTION>');
									print('<OPTION VALUE="3,000～3,999円">3,000～3,999円</OPTION>');
									print('<OPTION VALUE="4,000～4,999円">4,000～4,999円</OPTION>');
									print('<OPTION VALUE="5,000～5,999円">5,000～5,999円</OPTION>');
									print('<OPTION VALUE="6,000～7,999円">6,000～7,999円</OPTION>');
									print('<OPTION VALUE="8,000～9,999円">8,000～9,999円</OPTION>');
									print('<OPTION VALUE="10,000～14,999円">10,000～14,999円</OPTION>');
									print('<OPTION VALUE="15,000～19,999円">15,000～19,999円</OPTION>');
									print('<OPTION VALUE="20,000～29,999円">20,000～29,999円</OPTION>');
									print('<OPTION VALUE="30,000円～">30,000円～</OPTION>');
								print('</SELECT>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">予約</div>');
							print('</div>');
							print('<div class="column2_checkradio">');
								print('<label><input type="radio" name="inshokuten_reservation" value="1">予約可</label>');
								print('<label><input type="radio" name="inshokuten_reservation" value="2">完全予約制</label>');
								print('<label><input type="radio" name="inshokuten_reservation" value="3">予約不可</label>');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">支払い方法</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2_checkradio">');
								print('<label><input type="checkbox" name="inshokuten_payment[]" value="1">クレジットカード可</label>');
								print('<label><input type="checkbox" name="inshokuten_payment[]" value="2">電子マネー可</label>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_payment_optional" placeholder="支払い方法の補足事項">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">席数</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_seats" placeholder="例：カウンター5席、テーブル10席">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">駐車場</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2_checkradio">');
								print('<label><input type="radio" name="inshokuten_parking" value="1">あり</label>');
								print('<label><input type="radio" name="inshokuten_parking" value="2">なし</label>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_parking_optional" placeholder="駐車場の補足事項">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">ホームページ・SNSアカウント</div>');
								print('<span>半角英数字</span>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_url[]" value="">');
								print('<input type="text" name="inshokuten_url[]" value="">');
								print('<input type="text" name="inshokuten_url[]" value="">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">オープン日</div>');
							print('</div>');
							print('<div class="column2">');
								print('<input type="text" name="inshokuten_opened_date">');
							print('</div>');
						print('</div>');
						print('<div class="row">');
							print('<div class="column1_container">');
								print('<div class="column1">備考</div>');
								print('<span>全角かな/半角英数字</span>');
							print('</div>');
							print('<div class="column2"><textarea name="inshokuten_remarks"></textarea></div>');
						print('</div>');
					print('</div>');
				print('</div>');
			print('</form>');

			print('<div class="edit_inshokuten_button_container">');
			print('<input name="close_inshokuten" type="button" value="戻る">');
			print('<input name="confirm_inshokuten" type="button" value="確認する">');
			print('</div>');
		print('</div>');
	print('</div>');
}

function writeDialogAddInshokutenConfirm()
{
	print('<div class="dialog_add_inshokuten_background">');
		print('<div class="dialog_table">');
			print('<div class="dialog_table-cell">');
				print('<div id="dialog_add_inshokuten">');
					print('<div class="confirm_note">ご入力いただいた情報に間違いがないかご確認ください。</div>');
					print('<div class="frame">');
						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>飲食店名</div>');
							print('<div class="confirm_item_info dialog_inshokuten_name"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>ひらがな</div>');
							print('<div class="confirm_item_info dialog_inshokuten_read"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>ローマ字</div>');
							print('<div class="confirm_item_info dialog_inshokuten_english"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>郵便番号</div>');
							print('<div class="confirm_item_info dialog_inshokuten_postalcode"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>都道府県</div>');
							print('<div class="confirm_item_info dialog_inshokuten_pref"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>市区町村・番地</div>');
							print('<div class="confirm_item_info dialog_inshokuten_address"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>建物名・階数</div>');
							print('<div class="confirm_item_info dialog_inshokuten_address2"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>電話番号</div>');
							print('<div class="confirm_item_info dialog_inshokuten_phone"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>Email</div>');
							print('<div class="confirm_item_info dialog_inshokuten_email"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>店舗までのアクセス</div>');
							print('<div class="confirm_item_info dialog_inshokuten_station_optional"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>営業時間</div>');
							print('<div class="confirm_item_info dialog_inshokuten_hours"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>定休日</div>');
							print('<div class="confirm_item_info dialog_inshokuten_holiday"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>ジャンル1</div>');
							print('<div class="confirm_item_info dialog_inshokuten_main_genre"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>ジャンル2</div>');
							print('<div class="confirm_item_info dialog_inshokuten_sub_genre"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>ジャンル3</div>');
							print('<div class="confirm_item_info dialog_inshokuten_sub_genre2"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>日本酒メニュー</div>');
							print('<div class="confirm_item_info dialog_inshokuten_sake_count"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>サービスの特徴</div>');
							print('<div class="confirm_item_info dialog_inshokuten_store_style"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>予算</div>');
							print('<div class="confirm_item_info dialog_inshokuten_budget"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>予約</div>');
							print('<div class="confirm_item_info dialog_inshokuten_reservation"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>支払い方法</div>');
							print('<div class="confirm_item_info">');
								print('<div>');
									print('<span class="dialog_inshokuten_payment"></span>');
									print('<span class="dialog_inshokuten_payment2"></span>');
								print('</div>');
							print('</div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>席数</div>');
							print('<div class="confirm_item_info dialog_inshokuten_seats"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>駐車場</div>');
							print('<div class="confirm_item_info">');
								print('<div>');
									print('<span class="dialog_inshokuten_parking"></span>');
									print('<span class="dialog_inshokuten_parking2"></span>');
								print('</div>');
							print('</div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>ホームページ・SNSアカウント</div>');
							print('<div class="confirm_item_info dialog_inshokuten_url"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>オープン日</div>');
							print('<div class="confirm_item_info dialog_inshokuten_opened_date"></div>');
						print('</div>');

						print('<div class="alt">');
							print('<div class="confirm_item_title"><span></span>備考</div>');
							print('<div class="confirm_item_info dialog_inshokuten_remarks"></div>');
						print('</div>');

					print('</div>');

					print('<div class="edit_sake_button_container">');
						print('<input type="button" name="button_back" value="閉じる">');
						print('<input type="button" name="update_button" value="更新する">');
					print('</div>');
				print('</div>');
			print('</div>');
		print('</div>');
	print('</div>');
}

?>
