<?php

function write_search_bar()
{
	$keyword = $_GET['keyword'];
	$category = $_GET['category'] ? $_GET['category'] : 1;

    print('<!--#header-->');
    print('<nav class="header">');
      print('<div class="logo_navi_container">');
        print('<button type="button" class="hamburger is-closed animated fadeInLeft" data-toggle="offcanvas">');
          print('<span class="hamb-top"></span>');
          print('<span class="hamb-middle"></span>');
          print('<span class="hamb-bottom"></span>');
        print('</button>');

        print('<span id="logo">');
          print('<svg class="logoheart14024"><use xlink:href="#logoheart14024"/></svg>');
        print('</span>');

        print('<div class="mobile_search_container"></div>');

        print('<ul id="navigation_menu">');
          print('<li id="sakenomuguide">');
            print('<svg class="header_sakenomo2020"><use xlink:href="#sakenomo2020"/></svg>');
            print('<span>Sakenomoとは</span>');
          print('</li>');
          print('<li id="nonda" style="display:none">');
            print('<svg class="header_heart2020"><use xlink:href="#heart2020"/></svg>');
            print('<span>飲んだ</span>');
          print('</li>');
          print('<!--<li id="user_message">');
            print('<svg class="header_mail2620"><use xlink:href="#mail2620"/></svg>');
            print('<span>メッセージ</span>');
          print('</li>-->');
          print('<!--<li>');
              print('<svg class="header_help2020"><use xlink:href="#help2020"/></svg>');
              print('<span>ヘルプ</span>');
          print('</li>-->');

            $username = $_COOKIE['login_cookie'];

            if($username == "" || $username == null)
            {
              print('<li class="login_button_container">');
                print('<span id="login">');
                  print('<svg class="header_login2020"><use xlink:href="#login2020"/></svg>');
                  print('<span>ログイン</span>');
                print('</span>');
              print('</li>');
            }
            else
            {
              print('<li id="mypage_button_container">');
                print('<span id="mypage">');
                  print('<svg class="header_person2020"><use xlink:href="#person2020"/></svg>');
                  print('<span>マイページ</span>');
                print('</span>');
                print('<p class="header_arrow_icon"><span></span></p>');
                print('<div id="mypage_content">');
                  print('<p id="logout">ログアウト</p>');
                print('</div>');
              print('</li>');
            }

        print('</ul>');
      print('</div><!--class="logo-container"-->');

      print('<div class="searchbar_container">');
        print('<div id="searchbar">');

          print('<!-- write_portal_menu() -->');
          print('<div id="category_menu"> <!-- menu2 -->');
            print('<div id="category_menu_trigger">');
              print('<span>すべて</span>');
            print('</div>');

            print('<div id="search_content_position_adjust">');
              print('<div id="search_content">');
                print('<div id="close_main_menu" class="search_content_close"><svg class="category_close2020"><use xlink:href="#close2020"/></svg></div>');
                print('<div class="search_content_title">検索カテゴリ</div>');
                print('<ul class="menu">');
                  print('<li value="すべて">すべて</li>');
                  print('<li value="日本酒">日本酒</li>');
                  print('<li value="酒蔵">酒蔵</li>');
                  print('<!--<li value="酒販店">酒販店（日本酒を買えるお店）</li>-->');
                print('</ul>');
              print('</div>');
            print('</div>');
          print('</div>');

          print('<div class="border_line_invisible"></div>');

          print('<!--/#sake.form-action-->');
          print('<div id="sake" class="form-action show">');
            print('<form id="sake_form" name="form">');
              print('<input type="hidden" name="category" value=' .$category .'>');

              print('<div class="search_button_container">');
                print('<button id="sake_submit_search">');
                  print('<svg class="header_search2020"><use xlink:href="#search2020"/></svg>');
                print('</button>');
              print('</div>');

              print('<!--<div class="border_line"></div>-->');

              print('<div class="input_item">');
                print('<input id="sake_input" class="all_mode" autocomplete="off" placeholder="日本酒、酒蔵を検索" type="text" name="keyword" value =' .$keyword .'>');
                print('<ul id="sake_content"></ul>');
              print('</div>');

              /*print('<div class="border_line_invisible"></div>');

              print('<div id="sake_submit" class="trigger_search_container">');
                print('<svg class="trigger_search_pluslarge2020"><use xlink:href="#pluslarge2020"/></svg><!--spanの中から外に移動したhirasawa-->');
              print('</div><!--spanのid="sake_submit"をdivに移動したhirasawa-->');*/

              /*print('<div id="dialog_sake_option_background">');
                print('<div class="dialog_table">');
                  print('<div class="dialog_table-cell">');
                    print('<div id="sake_option">');
                      print('<div id="tab_search">');
                        print('<div class="close_sake_menu_container">');
                          print('<div id="close_sake_menu">');
                            print('<svg class="search_option_close2020"><use xlink:href="#close2020"/></svg>');
                          print('</div>');
                        print('</div>');
                        print('<ul>');
                          print('<li>');
                            print('<a href="#tabs-10">');
                              print('<svg class="search_option_sake3630 search_option_icon"><use xlink:href="#sake3630"/></svg>');
                              print('<span>日本酒</span>');
                            print('</a>');
                          print('</li>');
                          print('<div class="tab_search_border_line"></div>');
                          print('<li>');
                            print('<a href="#tabs-11">');
                              print('<svg class="search_option_brewery3630 search_option_icon"><use xlink:href="#brewery3630"/></svg>');
                              print('<span>酒蔵</span>');
                            print('</a>');
                          print('</li>');
                          print('<div class="tab_search_border_line"></div>');
                          print('<li>');
                            print('<a href="#tabs-12">');
                              print('<svg class="search_option_store3030 search_option_icon"><use xlink:href="#store3030"/></svg>');
                              print('<span>酒販店</span>');
                            print('</a>');
                          print('</li>');
                        print('</ul>');

                        print('<div id="tabs-10" class="form-action hide">');
                          print('<div class="sake_option_frame">');
                            print('<div class="searchSakeRow">');
                              print('<input id="sake_option_input" class="optional_input" autocomplete="off" placeholder="銘柄名、吟醸酒、山田錦など" type="text" name="sake_option_input">');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">都道府県</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="北海道">北海道</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="青森県">青森県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="岩手県">岩手県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="宮城県">宮城県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="秋田県">秋田県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="山形県">山形県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="福島県">福島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="茨城県">茨城県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="栃木県">栃木県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="群馬県">群馬県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="埼玉県">埼玉県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="千葉県">千葉県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="東京都">東京都</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="神奈川県">神奈川県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="新潟県">新潟県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="富山県">富山県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="石川県">石川県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="福井県">福井県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="山梨県">山梨県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="長野県">長野県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="岐阜県">岐阜県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="静岡県">静岡県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="愛知県">愛知県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="三重県">三重県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="滋賀県">滋賀県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="京都府">京都府</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="大阪府">大阪府</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="兵庫県">兵庫県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="奈良県">奈良県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="和歌山県">和歌山県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="鳥取県">鳥取県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="島根県">島根県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="岡山県">岡山県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="広島県">広島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="山口県">山口県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="徳島県">徳島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="香川県">香川県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="愛媛県">愛媛県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="高知県">高知県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="福岡県">福岡県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="佐賀県">佐賀県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="長崎県">長崎県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="熊本県">熊本県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="大分県">大分県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="宮城県">宮城県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="鹿児島県">鹿児島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_pref[]" value="沖縄県">沖縄県</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">特定名称</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="11">普通酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="21">本醸造酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="22">特別本醸造酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="31">純米酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="32">特別純米酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="33">純米吟醸酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="34">純米大吟醸酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="43">吟醸酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="44">大吟醸酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="44">大吟醸酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="99">非公開</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="special_name[]" value="90">その他</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">製法の特徴</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="11">無濾過</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="45">原酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="39">直汲み・直詰め</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="33">生酒・本生</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="35">生貯蔵酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="34">生詰酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="21">にごり酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="49">おりがらみ・うすにごり</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="51">スパークリング</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="42">きもと</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="43">山廃もと</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="38">袋吊り・斗瓶囲い・雫酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="41">槽しぼり</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="40">遠心分離</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="22">あらばしり</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="31">中取り・中汲み・中垂れ</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="32">責め・押切り</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="50">新酒・初しぼり・しぼりたて</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="37">ひやおろし・秋上がり</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="48">古酒・長期熟成酒</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="44">樽酒</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="46">生一本</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="sake_category[]" value="47">斗瓶取り・斗瓶囲い</span></label>-->');
                                print('<!--<span class="option_name"><input type="checkbox" name="sake_category[]" value="90">その他</span>-->');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow searchSakeRice">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">原料米</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kokusanmai">国産米</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yamadanishiki">山田錦</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="gohyakumangoku">五百万石</span></label>');

                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="omachi">雄町</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="aiyama">愛山</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="aokeisakehyakuyonjukkei">青系酒140系</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="akitashukomachi">秋田酒こまち</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="akinosei">秋の精</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ishikawasakesanjugo">石川酒30号</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ishikawamon">石川門</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="isenishiki">伊勢錦</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ipponjime">一本〆</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="inishienomai">いにしえの舞</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="iwai">祝</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ushuhomare">羽州誉</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="okuhomare">おくほまれ</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="oyamanishiki">雄山錦</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kairyoomachi">改良雄町</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kairyoshinko">改良信交</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kairyotattanryu">改良八反流</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kazenaruko">風鳴子</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kaminoho">神の穂</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kamenoo">亀の尾</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kannomai">神の舞</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kikusui">菊水</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kissui">亀粋</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kyonohana">京の華</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ginotome">ぎんおとめ</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ginginga">吟ぎんが</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ginsayaka">吟さやか</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ginnosato">吟のさと</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ginnosei">吟の精</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ginnoyume">吟の夢</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="gimpu">吟風</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ginfubuki">吟吹雪</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kinmonnishiki">金紋錦</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kuzuryu">九頭竜</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kuninohana">国の華</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kuranohana">蔵の華</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="koiomachi">こいおまち</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="gouriki">強力</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="koganebare">黄金晴</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kokuryomiyako">穀良都</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="koshikagura">越神楽</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="koshitanrei">越淡麗</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="koshinoshizuku">越の雫</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="kojonishiki">古城錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="saikaihyakusanjugogo">西海135号</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="saikaihyakusanjuyongo">西海134号</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="saitonoshizuku">西都の雫</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="sakanishiki">佐香錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="saganohana">さがの華</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="sakenohana">酒の華</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="sakepikari">サケピカリ</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="sekemirai">酒未来</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="sakemusashi">さけ武蔵</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="sachitama">幸玉</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="shizukuhime">しずく媛</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="jugemu">壽限無</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="shirakabanishiki">しらかば錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="shiragiku">白菊</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="shirotaenishiki">白妙錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="shinyamadahoichigo">新山田穂1号</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="shinriki">神力</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="suisei">彗星</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="senbonnishiki">千本錦</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="takanenishiki">たかね錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="takanemidori">たかねみどり</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="tajimagouriki">但馬強力</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="tatsunootoshigo">龍の落とし子</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="tamazakae">玉栄</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="chubusakekyujunanago">中部酒97号</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="chiyohonami">チヨホナミ</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="tsukushisakamai">つくし酒舞</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="tsuyubakaze">露葉風</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="dewasansan">出羽燦々</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="dewanosato">出羽の里</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="toujinohana">杜氏の華</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="toujinoyume">杜氏の夢</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="tochigisakejuyon">とちぎ酒14</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="tominokaori">富の香</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="toyokuni">豊国</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="nadanishiki">灘錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="nadahikari">なだひかり</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="niigatawase">新潟早生</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="ninkishizuku">人気しずく</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="nojobo">野條穂</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hakutsurunishiki">白鶴錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hatsushizuku">初雫</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hattan">八反</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hattannishiki">八反錦</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hattannishikinigo">八反錦2号</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hanaomoi">華想い</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hanakagura">はなかぐら</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hanafubuki">華吹雪</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hayaozeki">早大関</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="harimanishiki">播磨錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hikeisakerokujuichigo">飛系酒61号</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="bizenomachi">備前雄町</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hitachinishiki">ひたち錦</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hidahomare">ひだほまれ</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hidaminori">ひだみのり</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hitogokochi">ひとごこち</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hibaomachi">比婆雄町</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hyokeisakejuhachigo">兵系酒18号</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hyogoomachi">兵庫雄町</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hyogokitanishiki">兵庫北錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hyogokoinishiki">兵庫恋錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hyogonishiki">兵庫錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hyogoyumenishiki">兵庫夢錦</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hiyori">ひより</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hiroshimaomachi">広島雄町</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="fukunohana">フクノハナ</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="fusanomai">総の舞</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="funakiomachi">船木雄町</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="benkei">辨慶</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hohai">豊盃</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hokurikujunigo">北陸12号</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="hoshiakari">星あかり</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="homarefuji">誉富士</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="maikaze">舞風</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="mikinishiki">造酒錦</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="misatonishiki">美郷錦</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="miyamanishiki">美山錦</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yamasakeyongo">山酒4号（玉苗）</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yamadaho">山田穂</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yuinoka">結の香</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yuminariho">弓形穂</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yumeginka">夢吟香</span></label>-->');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yumesansui">夢山水</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="yumenoka">夢の香</span></label>');
                                print('<!--<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="rokkonishiki">六甲錦</span></label>-->');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="wakamizu">若水</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="wataribune">渡船</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rice_used[]" value="other">その他</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">精米歩合</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="seimai_rate[]" value="7">20%以下</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="seimai_rate[]" value="6">21%～30%</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="seimai_rate[]" value="5">31%～40%</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="seimai_rate[]" value="4">41%～50%</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="seimai_rate[]" value="3">51%～60%</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="seimai_rate[]" value="2">61%～70%</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="seimai_rate[]" value="1">71%以上</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow searchSakeAlcohol">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">Alc度数</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="alcohol_level[]" value="1">13度未満</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="alcohol_level[]" value="2">13度以上～14度未満</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="alcohol_level[]" value="3">14度以上～15度未満</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="alcohol_level[]" value="4">15度以上～16度未満</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="alcohol_level[]" value="5">16度以上～17度未満</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="alcohol_level[]" value="6">17度以上～18度未満</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="alcohol_level[]" value="7">18度以上</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">日本酒度</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="jsake_level[]" value="1">-6.0以下</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="jsake_level[]" value="2">-5.9～-3.5</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="jsake_level[]" value="3">-3.4～-1.5</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="jsake_level[]" value="4">-1.4～+1.4</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="jsake_level[]" value="5">+1.5～+3.4</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="jsake_level[]" value="6">+3.5～+5.9</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="jsake_level[]" value="7">+6.0以上</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<!--<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">酸度</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="oxidation_level[]" value="1">0.5以下</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="oxidation_level[]" value="2">0.6～1.0</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="oxidation_level[]" value="3">1.1～1.5</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="oxidation_level[]" value="4">1.6～2.0</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="oxidation_level[]" value="5">2.1～2.5</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="oxidation_level[]" value="6">2.6以上</span></label>');
                              print('</div>');
                            print('</div>-->');

                            print('<!--<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">ユーザー満足度</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="rank[]" value="1">0～1.0</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rank[]" value="2">1.1～2.0</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rank[]" value="3">2.1～3.0</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rank[]" value="4">3.1～4.0</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="rank[]" value="5">4.1～5.0</span></label>');
                              print('</div>');
                            print('</div>-->');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">入力状況</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<SELECT id="input_sake_develop" name="sake_develop">');
                                  print('<OPTION VALUE="">入力状況</OPTION>');
                                  print('<OPTION VALUE="1">完成</OPTION>');
                                  print('<OPTION VALUE="2">途中</OPTION>');
                                  print('<OPTION VALUE="3">未完成</OPTION>');
                                print('</SELECT>');
                                print('<input id="pic_checkbox" type="checkbox" name="pic_checkbox" value = "1">');
                                print('<span id="pic_included">pic</span>');
                              print('</div>');
                            print('</div> <!-- end of firstrow -->');
                          print('</div> <!-- sake_option_frame -->');

                          print('<div class="sake_option_search_button_container">');
                            print('<button type="submit" name="sake_option">検索</button>');
                          print('</div>');
                        print('</div> <!-- tab11 -->');

                        print('<div id="tabs-11" class="form-action hide">');
                          print('<div class="sake_option_frame">');
                            print('<div class="searchSakeRow">');
                              print('<input id="sakagura_option_input" class="optional_input" autocomplete="off" placeholder="酒蔵名" type="text" name="sakagura_option_input">');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">都道府県</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="北海道">北海道</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="青森県">青森県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="岩手県">岩手県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="宮城県">宮城県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="秋田県">秋田県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="山形県">山形県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="福島県">福島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="茨城県">茨城県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="栃木県">栃木県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="群馬県">群馬県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="埼玉県">埼玉県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="千葉県">千葉県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="東京都">東京都</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="神奈川県">神奈川県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="新潟県">新潟県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="富山県">富山県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="石川県">石川県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="福井県">福井県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="山梨県">山梨県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="長野県">長野県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="岐阜県">岐阜県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="静岡県">静岡県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="愛知県">愛知県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="三重県">三重県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="滋賀県">滋賀県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="京都府">京都府</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="大阪府">大阪府</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="兵庫県">兵庫県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="奈良県">奈良県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="和歌山県">和歌山県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="鳥取県">鳥取県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="島根県">島根県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="岡山県">岡山県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="広島県">広島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="山口県">山口県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="徳島県">徳島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="香川県">香川県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="愛媛県">愛媛県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="高知県">高知県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="福岡県">福岡県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="佐賀県">佐賀県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="長崎県">長崎県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="熊本県">熊本県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="大分県">大分県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="宮城県">宮城県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="鹿児島県">鹿児島県</span></label>');
                                print('<label><span class="option_name"><input type="checkbox" name="sakagura_pref[]" value="沖縄県">沖縄県</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">酒蔵見学</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="observation" value="1">可');
                                print('</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">酒造組合登録</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<SELECT name="kumiai">');
                                  print('<OPTION VALUE="">指定なし</OPTION>');
                                  print('<OPTION VALUE=10>あり</OPTION>');
                                  print('<OPTION VALUE=11>なし</OPTION>');
                                  print('<OPTION VALUE=12>不明</OPTION>');
                                print('</SELECT>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">国税庁登録</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<SELECT name="kokuzei">');
                                print('<OPTION VALUE="">指定なし</OPTION>');
                                print('<OPTION VALUE=10>あり</OPTION>');
                                print('<OPTION VALUE=11>なし</OPTION>');
                                print('<OPTION VALUE=12>不明</OPTION>');
                                print('</SELECT>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">ステータス</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<SELECT name="status">');
                                  print('<OPTION VALUE="">指定なし</OPTION>');
                                  print('<OPTION VALUE=10>active</OPTION>');
                                  print('<OPTION VALUE=11>inactive</OPTION>');
                                  print('<OPTION VALUE=12>一時製造休止</OPTION>');
                                  print('<OPTION VALUE=13>営業不明</OPTION>');
                                print('</SELECT>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">プライオリティ</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<SELECT id="dialog_priority" name="priority">');
                                  print('<OPTION VALUE="">指定なし</OPTION>');
                                  print('<OPTION VALUE="1">S</OPTION>');
                                  print('<OPTION VALUE="2">A</OPTION>');
                                  print('<OPTION VALUE="3">B</OPTION>');
                                  print('<OPTION VALUE="4">C</OPTION>');
                                  print('<OPTION VALUE="5">D</OPTION>');
                                  print('<OPTION VALUE="6">E</OPTION>');
                                  print('<OPTION VALUE="7">X</OPTION>');
                                print('</SELECT>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">データ状況</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<SELECT id="sakagura_develop" name="sakagura_develop">');
                                  print('<OPTION VALUE="">指定なし</OPTION>');
                                  print('<OPTION VALUE="1">完成</OPTION>');
                                  print('<OPTION VALUE="2">途中</OPTION>');
                                  print('<OPTION VALUE="3">未完成</OPTION>');
                                print('</SELECT>');
                              print('</div>');
                            print('</div>');
                          print('</div>');

                          print('<div class="sake_option_search_button_container">');
                            print('<button type="submit" name="sakagura_option">検索</button>');
                          print('</div>');
                        print('</div>');

                        print('<div id="tabs-12" class="form-action hide">');
                          print('<div class="sake_option_frame">');
                            print('<div class="searchSakeRow">');
                              print('<input id="syuhanten_option_input" class="optional_input" autocomplete="off" placeholder="店名、取扱い銘柄、駅名など" type="text" name="syuhanten_option_input">');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">取扱い日本酒</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="1">1～10種類');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="2">11～20種類');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="3">21～30種類');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="4">31～40種類');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="5">41～50種類');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="6">51～70種類');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="7">71～100種類');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_hyouka[]" value="8">101種類以上');
                                print('</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">都道府県</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="北海道">北海道');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="青森県">青森県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="岩手県">岩手県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="宮城県">宮城県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="秋田県">秋田県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="山形県">山形県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="福島県">福島県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="茨城県">茨城県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="栃木県">栃木県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="群馬県">群馬県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="埼玉県">埼玉県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="千葉県">千葉県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="東京都">東京都');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="神奈川県">神奈川県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="新潟県">新潟県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="富山県">富山県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="石川県">石川県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="福井県">福井県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="山梨県">山梨県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="長野県">長野県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="岐阜県">岐阜県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="静岡県">静岡県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="愛知県">愛知県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="三重県">三重県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="滋賀県">滋賀県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="京都府">京都府');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="大阪府">大阪府');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="兵庫県">兵庫県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="奈良県">奈良県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="和歌山県">和歌山県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="鳥取県">鳥取県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="島根県">島根県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="岡山県">岡山県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="広島県">広島県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="山口県">山口県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="徳島県">徳島県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="香川県">香川県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="愛媛県">愛媛県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="高知県">高知県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="福岡県">福岡県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="佐賀県">佐賀県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="長崎県">長崎県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="熊本県">熊本県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="大分県">大分県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="宮城県">宮城県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="鹿児島県">鹿児島県');
                                print('</span></label>');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="syuhanten_pref[]" value="沖縄県">沖縄県');
                                print('</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">日曜営業</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="pic_checkbox" value="1">あり');
                                print('</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">駐車場</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<label><span class="option_name">');
                                  print('<input type="checkbox" name="pic_checkbox" value="1">あり');
                                print('</span></label>');
                              print('</div>');
                            print('</div>');

                            print('<div class="searchSakeRow">');
                              print('<div class="searchColumn1">');
                                print('<span class="searchColumn1_item">データ状況</span>');
                                print('<p class="plus_minus_icon"><span></span><span></span></p>');
                              print('</div>');
                              print('<div class="searchColumn2">');
                                print('<SELECT id="syuhanten_develop" name="syuhanten_develop">');
                                  print('<OPTION VALUE="">指定なし</OPTION>');
                                  print('<OPTION VALUE="1">完成</OPTION>');
                                  print('<OPTION VALUE="2">途中</OPTION>');
                                  print('<OPTION VALUE="3">未完成</OPTION>');
                                print('</SELECT>');
                              print('</div>');
                            print('</div>');

                          print('</div> <!-- sake_option_frame -->');

                          print('<div class="sake_option_search_button_container">');
                            print('<button type="submit" name="syuhanten_option">検索</button>');
                          print('</div>');

                        print('</div> <!-- tabs-12 -->');
                      print('</div> <!-- tab_search -->');
                    print('</div> <!--sake_option -->');
                  print('</div>');
                print('</div>');
              print('</div>');*/

            print('</form><!--sake_form -->');
          print('</div> <!--sake -->');
        print('</div><!--入力されていなかった閉じタグ-->');
      print('</div><!--class="searchbar-container"-->');
    print('</nav>');
}

?>
